TRAIN:
  ENABLE: True
  DATASET: bkinetics
  BATCH_SIZE: 144
  #BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 25
  CHECKPOINT_FILE_PATH: MViTv2_S_16x4_k400_f302660347.pyth
  #CHECKPOINT_FILE_PATH: projects/mvitv2/MViTv2_S_16x4_k400.pyth
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_EPOCH_RESET: True
  MIXED_PRECISION: True
  AUTO_RESUME: True
TEST:
  ENABLE: True
  DATASET: bkinetics
  BATCH_SIZE: 128
  #BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: torchvision
  NUM_FRAMES: 16
  SAMPLING_RATE: 24
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: data/annotations/standard/foreground_background
  PATH_PREFIX: data/videos/cropped
  #PATH_TO_DATA_DIR: dataset/annotations/fgbgmixup
  #PATH_PREFIX: dataset/videos
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  MULTI_LABEL: True
  ENSEMBLE_METHOD: max
FG_BG_MIXUP:
  ENABLE: True
  CONCAT_BG_FRAMES:
    ENABLE: True
    RATIO: 0.0 # NUM_FRAMES + 1.0 * NUM_FRAMES # change to 0.5, 1.0, 2.0, 4.0, 8.0, 16.0 ...
    SUBSAMPLE_CONCAT_FRAMES: True
  SUBTRACT_BG:
    ENABLE: True
    ALPHA_MIN: 0.0
    ALPHA_MAX: 1.0
    SCHEDULER: linear
  MIX_ON_EVAL: True
TENSORBOARD:
  ENABLE: True
MVIT:
  ZERO_DECAY_POS_CLS: False
  USE_ABS_POS: False
  REL_POS_SPATIAL: True
  REL_POS_TEMPORAL: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]]
  DROPOUT_RATE: 0.0
  DIM_MUL_IN_ATT: True
  RESIDUAL_POOLING: True
AUG:
  NUM_SAMPLE: 1
  ENABLE: False
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: False
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  ZERO_WD_1D_PARAM: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR_SCALE_NUM_SHARDS: True
  BASE_LR: 0.0001
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 30.0
  LR_POLICY: cosine
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 14
  ARCH: mvit
  MODEL_NAME: MViTFGBGMixup
  LOSS_FUNC: bce_logit
  HEAD_ACT: none
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 4
#NUM_GPUS: 2
NUM_SHARDS: 1
USE_SBATCH: False
RNG_SEED: 0
LOG_PERIOD: 1
OUTPUT_DIR: results/model=mvit2-base_bg_concat=0.0_minus_bg
