TRAIN:
  ENABLE: True
  DATASET: bkinetics
  BATCH_SIZE: 8
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 25
  CHECKPOINT_FILE_PATH: SLOWONLY_8x8_R50.pkl
  CHECKPOINT_TYPE: caffe2
  MIXED_PRECISION: True
  AUTO_RESUME: True
TEST:
  ENABLE: False
  DATASET: nkinetics
  BATCH_SIZE: 8
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 24
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: data/annotations/standard/foreground_background
  PATH_PREFIX: data/videos/cropped
  MULTI_LABEL: True
  ENSEMBLE_METHOD: max
  SPATIAL_SAMPLING: False
  TARGET_FPS: 24
FG_BG_MIXUP:
  ENABLE: True
  CONCAT_BG_FRAMES:
    ENABLE: True
    RATIO: 0.0 # NUM_FRAMES + 1.0 * NUM_FRAMES # change to 0.5, 1.0, 2.0, 4.0, 8.0, 16.0 ...
    SUBSAMPLE_CONCAT_FRAMES: True
  SUBTRACT_BG:
    ENABLE: True
    ALPHA_MIN: 0.0
    ALPHA_MAX: 1.0
    SCHEDULER: linear
  MIX_ON_EVAL: True
AUG:
  ENABLE: False
TENSORBOARD:
  ENABLE: True
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 2.5e-1
  LR_POLICY: cosine
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 2.5e-2
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 14
  ARCH: slow
  MODEL_NAME: ResNetFGBGMixup
  HEAD_ACT: none
  LOSS_FUNC: bce_logit
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 2
NUM_SHARDS: 1
USE_SBATCH: False
RNG_SEED: 0
LOG_PERIOD: 1
OUTPUT_DIR: 'results/model=slow_r50_bg_concat=0.0_minus_bg_sub'
